# Generated by Django 5.2.1 on 2025-06-02 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='nickname',
            new_name='nickName',
        ),
    ]
