# Generated by Django 5.2.1 on 2025-05-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuscore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuscore',
            old_name='title',
            new_name='total',
        ),
    ]
