# Generated by Django 5.2.1 on 2025-06-10 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='id',
        ),
    ]
